name: Run every 10 minutes

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest  # Choose your environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run your script
        run: |
          # Run your command or script here
          echo "This script runs every 10 minutes!"
